# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TypingUsedPod' do
  use_frameworks!

  # Pods for TypingUsedPod
  
  pod 'CLTypingLabel', '~> 0.4.0'

end
